# Generated by Django 4.2.1 on 2023-05-30 15:12

from django.db import migrations, models
import django.db.models.deletion
import dnd.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opevneni',
            fields=[
                ('typ', models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='Typ opevnění')),
            ],
            options={
                'verbose_name': 'Opevnění',
                'verbose_name_plural': 'Opevnění',
                'ordering': ['typ'],
            },
        ),
        migrations.CreateModel(
            name='PolitickeUsporadani',
            fields=[
                ('nazev', models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='Název')),
                ('popis', models.CharField(blank=True, help_text='Popis jak daný systém funguje', max_length=45, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Politické uspořádání',
                'verbose_name_plural': 'Politická uspořádání',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Povaha',
            fields=[
                ('povaha', models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='Typ povahy')),
            ],
            options={
                'verbose_name': 'Povaha',
                'verbose_name_plural': 'Povahy',
                'ordering': ['povaha'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('nazev', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Jméno regionu')),
                ('podnebi', models.CharField(choices=[('tropicke', 'tropicke'), ('sebtropicke', 'sebtropicke'), ('mírné', 'mírné'), ('subpolární', 'subpolární'), ('polární', 'polární')], max_length=50, verbose_name='Podnebí')),
                ('popis', models.TextField(blank=True, help_text='Popište základní geografické části regionu, jeho historii a státy které se zde nachází', verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiony',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('nazev', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rozloha', models.CharField(choices=[('obrovská', 'obrovská'), ('velka', 'velka'), ('stredni', 'stredni'), ('mala', 'mala')], max_length=50)),
                ('changed_filename', models.CharField(default='vlajka', editable=False, max_length=50)),
                ('vlajka', models.ImageField(blank=True, upload_to=dnd.models.uploadnuto, verbose_name='Vlajka')),
                ('politicke_usporadani', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dnd.politickeusporadani')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.region')),
            ],
            options={
                'verbose_name': 'Stát',
                'verbose_name_plural': 'Státy',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='TypMesta',
            fields=[
                ('typ', models.CharField(help_text='Přístav, vesnice, město etc.', max_length=50, primary_key=True, serialize=False, verbose_name='Typ města')),
            ],
            options={
                'verbose_name': 'Typ města',
                'verbose_name_plural': 'Typy města',
                'ordering': ['typ'],
            },
        ),
        migrations.CreateModel(
            name='Vladce',
            fields=[
                ('idvladce', models.IntegerField(primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=45, verbose_name='Jméno')),
                ('rasa', models.CharField(choices=[('elf', 'Elf'), ('trpaslík', 'Trpaslík'), ('člověk', 'Člověk'), ('gnóm', 'Gnóm'), ('půlork', 'Půlork'), ('drakorozený', 'Drakorozený'), ('zvíře', 'zvíře'), ('půlčík', 'Půlčík'), ('půlelf', 'Půl-elf'), ('tiefling', 'Tiefling'), ('jine', 'Jiné')], max_length=45)),
                ('vek', models.IntegerField(default=20, verbose_name='Věk')),
                ('vyska', models.IntegerField(blank=True, verbose_name='Výška')),
                ('oci', models.CharField(blank=True, max_length=45, verbose_name='Oči')),
                ('oblicej', models.CharField(blank=True, max_length=45, verbose_name='Obličej')),
                ('kladne_vlastnosti', models.CharField(blank=True, max_length=150, verbose_name='Kladné vlastnosti')),
                ('zaporne_vlastnosti', models.CharField(blank=True, max_length=150, verbose_name='Záporné vlastnosti')),
                ('specifickeZnaky', models.CharField(blank=True, help_text='Tetování etc.', max_length=45, verbose_name='Specifické znaky')),
                ('vztahHraci', models.CharField(blank=True, max_length=150, verbose_name='Vztah k hráčům')),
                ('changed_filename', models.CharField(default='vladce', editable=False, max_length=50)),
                ('fotka', models.ImageField(upload_to=dnd.models.uploadnuto, verbose_name='Fotka')),
                ('povaha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dnd.povaha', verbose_name='Povaha')),
                ('stat_nazev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.stat', verbose_name='Stát')),
            ],
            options={
                'verbose_name': 'Vládce',
                'verbose_name_plural': 'Vládci',
                'ordering': ['jmeno'],
            },
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('idnpc', models.IntegerField(primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=45, null=True)),
                ('prijmeni', models.CharField(max_length=45)),
                ('rasa', models.CharField(choices=[('elf', 'Elf'), ('trpaslík', 'Trpaslík'), ('člověk', 'Člověk'), ('gnóm', 'Gnóm'), ('půlork', 'Půlork'), ('drakorozený', 'Drakorozený'), ('zvíře', 'zvíře'), ('půlčík', 'Půlčík'), ('půlelf', 'Půl-elf'), ('tiefling', 'Tiefling'), ('jine', 'Jiné')], max_length=45)),
                ('vek', models.IntegerField(default=20, verbose_name='Věk')),
                ('vyska', models.IntegerField(null=True, verbose_name='Výška')),
                ('oci', models.CharField(max_length=45, null=True, verbose_name='Oči')),
                ('oblicej', models.CharField(max_length=45, null=True, verbose_name='Obličej')),
                ('kladne_vlastnosti', models.CharField(blank=True, max_length=150, verbose_name='Kladné vlastnosti')),
                ('zaporne_vlastnosti', models.CharField(blank=True, max_length=150, verbose_name='Záporné vlastnosti')),
                ('specifickeZnaky', models.CharField(blank=True, help_text='Tetování etc.', max_length=45, verbose_name='Specifické znaky')),
                ('vztahHraci', models.CharField(blank=True, max_length=150, verbose_name='Vztah k hráčům')),
                ('changed_filename', models.CharField(default='NPCs/', editable=False, max_length=50)),
                ('fotka', models.ImageField(blank=True, upload_to=dnd.models.uploadnuto, verbose_name='Fotka')),
                ('povaha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dnd.povaha', verbose_name='Povaha')),
            ],
            options={
                'verbose_name': 'NPC',
                'verbose_name_plural': 'NPCs',
                'ordering': ['prijmeni'],
            },
        ),
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('nazev', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Název města')),
                ('pocet_obyvatel', models.IntegerField(verbose_name='Počet obyvatel města')),
                ('rozloha', models.ImageField(upload_to=dnd.models.uploadnuto)),
                ('hlavni', models.CharField(choices=[(('ano', 'Ano'), ('ne', 'Ne'))], max_length=20, verbose_name='Jedná se o hlavní město?')),
                ('npc_idnpc', models.ManyToManyField(to='dnd.npc')),
                ('opevneni_typ', models.ManyToManyField(to='dnd.opevneni')),
                ('stat_nazev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.stat')),
                ('typ_mesta_typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.typmesta')),
                ('vladce_idvladce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.vladce')),
            ],
        ),
        migrations.CreateModel(
            name='Budova',
            fields=[
                ('nazev', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('typ_budovy', models.CharField(max_length=50)),
                ('mesto_nazev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.mesto')),
            ],
        ),
    ]
