# Generated by Django 4.2.1 on 2023-05-30 18:01

from django.db import migrations, models
import django.db.models.deletion
import dnd.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_alter_budova_options_remove_mesto_npc_idnpc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spravce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Správce města',
                'verbose_name_plural': 'Správci měst',
                'ordering': ['spravce'],
            },
        ),
        migrations.CreateModel(
            name='VladceStatu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.stat', verbose_name='Stát')),
            ],
            options={
                'verbose_name': 'Vládce Státu',
                'verbose_name_plural': 'Vládci Států',
                'ordering': ['vladce'],
            },
        ),
        migrations.AlterModelOptions(
            name='mesto',
            options={'ordering': ['nazev'], 'verbose_name': 'Město', 'verbose_name_plural': 'Města'},
        ),
        migrations.RemoveField(
            model_name='mesto',
            name='spravce',
        ),
        migrations.AddField(
            model_name='mesto',
            name='changed_filename',
            field=models.CharField(default='mesto_vesnice', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='npc',
            name='stat_nazev',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dnd.stat', verbose_name='Stát'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budova',
            name='vlastnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.npc'),
        ),
        migrations.AlterField(
            model_name='mesto',
            name='hlavni',
            field=models.CharField(choices=[('ano', 'Ano'), ('ne', 'Ne')], max_length=20, verbose_name='Jedná se o hlavní město?'),
        ),
        migrations.AlterField(
            model_name='mesto',
            name='opevneni_typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.opevneni', verbose_name='Typ opevnění'),
        ),
        migrations.AlterField(
            model_name='mesto',
            name='rozloha',
            field=models.ImageField(upload_to=dnd.models.upload_mesto),
        ),
        migrations.AlterField(
            model_name='npc',
            name='oblicej',
            field=models.CharField(blank=True, max_length=45, verbose_name='Obličej'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='oci',
            field=models.CharField(blank=True, max_length=45, verbose_name='Oči'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='povaha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.povaha', verbose_name='Povaha'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='vyska',
            field=models.IntegerField(blank=True, verbose_name='Výška'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='vztahHraci',
            field=models.CharField(blank=True, choices=[('friendly', 'Přátelský'), ('neutrall', 'Neutrální'), ('hostile', 'Nepřátelský')], max_length=150, verbose_name='Vztah k hráčům'),
        ),
        migrations.DeleteModel(
            name='Vladce',
        ),
        migrations.AddField(
            model_name='vladcestatu',
            name='vladce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.npc', verbose_name='Vládce státu'),
        ),
        migrations.AddField(
            model_name='spravce',
            name='mesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.mesto', verbose_name='Město'),
        ),
        migrations.AddField(
            model_name='spravce',
            name='spravce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.npc', verbose_name='Správce města'),
        ),
    ]
