# Generated by Django 4.2.1 on 2023-05-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0003_spravce_vladcestatu_alter_mesto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesto',
            name='opevneni_typ',
        ),
        migrations.AddField(
            model_name='mesto',
            name='opevneni_typ',
            field=models.ManyToManyField(to='dnd.opevneni', verbose_name='Typ opevnění'),
        ),
    ]
