# Generated by Django 4.2.1 on 2023-05-31 10:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0004_remove_mesto_opevneni_typ_mesto_opevneni_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='podnebi',
            field=models.CharField(choices=[('tropicke', 'tropicke'), ('subtropicke', 'subtropicke'), ('mírné', 'mírné'), ('subpolární', 'subpolární'), ('polární', 'polární')], max_length=50, verbose_name='Podnebí'),
        ),
        migrations.CreateModel(
            name='StatTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sila', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Síla')),
                ('obratnost', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Obratnost')),
                ('vydrz', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Výdrž')),
                ('inteligence', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Inteligence')),
                ('moudrost', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Inteligence')),
                ('charisma', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Charisma')),
                ('sila_modifier', models.IntegerField(editable=False)),
                ('obratnost_modifier', models.IntegerField(editable=False)),
                ('vydrz_modifier', models.IntegerField(editable=False)),
                ('inteligence_modifier', models.IntegerField(editable=False)),
                ('moudrost_modifier', models.IntegerField(editable=False)),
                ('charisma_modifier', models.IntegerField(editable=False)),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.npc', verbose_name='NPC')),
            ],
            options={
                'verbose_name': 'Schopnosti',
                'verbose_name_plural': 'Staty',
                'ordering': ['npc'],
            },
        ),
    ]
