# Generated by Django 4.2.1 on 2023-05-31 14:54

from django.db import migrations, models
import dnd.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0005_alter_region_podnebi_stattable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stattable',
            options={'ordering': ['npc'], 'verbose_name': 'Schopnosti', 'verbose_name_plural': 'Schopnosti'},
        ),
        migrations.RemoveField(
            model_name='mesto',
            name='rozloha',
        ),
        migrations.AddField(
            model_name='mesto',
            name='mapa',
            field=models.ImageField(blank=True, upload_to=dnd.models.upload_mesto),
        ),
        migrations.AddField(
            model_name='region',
            name='changed_filename',
            field=models.CharField(default='mapa', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='region',
            name='mapa',
            field=models.ImageField(blank=True, upload_to=dnd.models.uploadnuto, verbose_name='Vlajka'),
        ),
    ]
