# Generated by Django 4.2.1 on 2023-06-01 14:42

from django.db import migrations, models
import dnd.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0006_alter_stattable_options_remove_mesto_rozloha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='mapa',
            field=models.ImageField(blank=True, upload_to=dnd.models.upload_mapa, verbose_name='Mapa'),
        ),
    ]
