# Generated by Django 4.2.1 on 2023-06-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0007_alter_region_mapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geografie',
            fields=[
                ('nazev', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Název místa')),
                ('typ', models.CharField(choices=[('hora', 'Hora'), ('pohori', 'Pohoří'), ('hvozd', 'Hvozd'), ('les', 'Les'), ('poust', 'Poušť'), ('kopce', 'Kopce')], max_length=10, verbose_name='Typ místa')),
                ('zajimavost', models.TextField(blank=True, help_text='Nejvyšší hora, historie místa etc.', verbose_name='Zajímavosti')),
            ],
            options={
                'verbose_name': 'Geografie',
                'verbose_name_plural': 'Geografie',
                'ordering': ['nazev'],
            },
        ),
        migrations.AlterField(
            model_name='npc',
            name='rasa',
            field=models.CharField(choices=[('elf', 'Elf'), ('trpaslík', 'Trpaslík'), ('člověk', 'Člověk'), ('gnóm', 'Gnóm'), ('půlork', 'Půl-ork'), ('drakorozený', 'Drakorozený'), ('půlčík', 'Půlčík'), ('půlelf', 'Půl-elf'), ('tiefling', 'Tiefling'), ('jine', 'Jiné')], max_length=45),
        ),
        migrations.AddField(
            model_name='region',
            name='geografie',
            field=models.ManyToManyField(to='dnd.geografie'),
        ),
    ]
