# Generated by Django 4.2.1 on 2023-06-02 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0008_geografie_alter_npc_rasa_region_geografie'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestingPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50, verbose_name='Název místa')),
                ('popis', models.CharField(blank=True, help_text='Popis místa', max_length=45, verbose_name='Popis')),
                ('typ', models.CharField(choices=[('dungeon', 'Dungeon'), ('jeskyně', 'Jeskyně'), ('place_of_power', 'Místo moci')], max_length=20, verbose_name='Typ místa')),
                ('mesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.mesto', verbose_name='Město')),
            ],
        ),
    ]
