# Generated by Django 4.2.1 on 2023-06-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0011_actions_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='dc',
            field=models.IntegerField(default=10, verbose_name='DC'),
        ),
        migrations.AddField(
            model_name='actions',
            name='perception',
            field=models.IntegerField(default=10, verbose_name='Vnímání'),
        ),
    ]
