# Generated by Django 4.2.1 on 2023-06-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0012_actions_dc_actions_perception'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='politicke_usporadani',
        ),
        migrations.AddField(
            model_name='stat',
            name='politicke_usporadani',
            field=models.ManyToManyField(to='dnd.politickeusporadani', verbose_name='Politické uspořádání'),
        ),
    ]
