# Generated by Django 4.2.1 on 2023-06-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0014_stattable_ac_stattable_health_die_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='perception',
        ),
        migrations.AddField(
            model_name='stattable',
            name='perception',
            field=models.IntegerField(default=10, verbose_name='Vnímání'),
        ),
    ]
