# Generated by Django 4.2.1 on 2023-06-02 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0015_remove_actions_perception_stattable_perception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='bonus_to_hit',
            field=models.IntegerField(blank=True, verbose_name='Bonus k zásahu'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='dc',
            field=models.IntegerField(blank=True, default=10, verbose_name='DC'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='dmg_dice',
            field=models.CharField(blank=True, help_text='Formát 1k8', max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+k[0-9]+(\\+[0-9]+)?$', 'Zadej formát s "k".')], verbose_name='Kostky poškození'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='reach',
            field=models.IntegerField(blank=True, verbose_name='Dosah'),
        ),
        migrations.AlterField(
            model_name='stattable',
            name='roll_health',
            field=models.CharField(blank=True, help_text='Formát 1k8', max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+k[0-9]+(\\+[0-9]+)?$', 'Zadej formát s "k".')], verbose_name='Kostky životů'),
        ),
    ]
