# Generated by Django 4.2.1 on 2023-06-02 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0016_alter_actions_bonus_to_hit_alter_actions_dc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='bonus_to_hit',
            field=models.IntegerField(verbose_name='Bonus k zásahu'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='dc',
            field=models.IntegerField(default=10, verbose_name='DC'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='dmg_dice',
            field=models.CharField(help_text='Formát 1k8', max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+k[0-9]+(\\+[0-9]+)?$', 'Zadej formát s "k".')], verbose_name='Kostky poškození'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='max_dmg',
            field=models.IntegerField(verbose_name='Maximální možné poškození'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='range',
            field=models.CharField(help_text='Formát 4/6', max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+/[0-9]+$', 'Zadej formát s "/".')], verbose_name='Dosah na dálku'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='reach',
            field=models.IntegerField(verbose_name='Dosah'),
        ),
    ]
